# Generated by Django 4.2.3 on 2023-07-28 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import plannings.python_scripts.plannings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('has_child_in_college', models.BooleanField(default=False)),
                ('has_child_in_school', models.BooleanField(default=False)),
                ('total_participations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('etablissement', models.CharField(choices=[('COL', 'College'), ('EC', 'Ecole')], max_length=5)),
                ('planning', models.JSONField(default=plannings.python_scripts.plannings.generate_empty_periode)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('categorie', models.CharField(choices=[('C1', 'Cycle 1'), ('C2', 'Cycle 2'), ('C3', 'Cycle 3'), ('COL', 'College'), ('EQ', 'Equipier')], max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('commentaire', models.CharField(blank=True, max_length=1500)),
                ('famille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plannings.family')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.periode')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], max_length=15)),
                ('creneau', models.CharField(choices=[('matin', 'Matin'), ('midi', 'Midi'), ('soir', 'Soir')], max_length=10)),
                ('horaire_arrivee', models.TimeField(blank=True, null=True)),
                ('horaire_depart', models.TimeField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.inscription')),
            ],
        ),
    ]
