# Generated by Django 4.2.3 on 2023-07-20 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='has_child_in_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_child_in_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('commentaire', models.CharField(blank=True, max_length=1500)),
                ('famille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plannings.family')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauInscriptionEquipier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('semaine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi')], max_length=15)),
                ('creneau', models.CharField(choices=[('MATIN', 'Matin'), ('MIDI', 'Midi'), ('SOIR', 'Soir')], max_length=10)),
                ('id_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauInscriptionEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_enfant', models.CharField(choices=[('C1', 'Cycle 1'), ('C2', 'Cycle 2'), ('C3', 'Cycle 3'), ('COL', 'College')], max_length=10)),
                ('periode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('semaine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi')], max_length=15)),
                ('creneau', models.CharField(choices=[('MATIN', 'Matin'), ('MIDI', 'Midi'), ('SOIR', 'Soir')], max_length=10)),
                ('horaire_arrivee', models.TimeField()),
                ('horaire_depart', models.TimeField()),
                ('id_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.inscription')),
            ],
        ),
    ]
