# Generated by Django 4.2.3 on 2023-07-28 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='annee',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2023)]),
            preserve_default=False,
        ),
    ]
