# Generated by Django 4.2.3 on 2023-07-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0002_periode_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periode',
            name='etablissement',
        ),
    ]
