# Generated by Django 4.2.3 on 2023-07-20 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0002_alter_family_has_child_in_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_enfant', models.CharField(blank=True, choices=[('C1', 'Cycle 1'), ('C2', 'Cycle 2'), ('C3', 'Cycle 3'), ('COL', 'College')], max_length=10, null=True)),
                ('periode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('semaine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], max_length=15)),
                ('creneau', models.CharField(choices=[('matin', 'Matin'), ('midi', 'Midi'), ('soir', 'Soir')], max_length=10)),
                ('horaire_arrivee', models.TimeField(blank=True, null=True)),
                ('horaire_depart', models.TimeField(blank=True, null=True)),
                ('id_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.inscription')),
            ],
        ),
        migrations.RemoveField(
            model_name='creneauinscriptionequipier',
            name='id_inscription',
        ),
        migrations.DeleteModel(
            name='CreneauInscriptionEnfant',
        ),
        migrations.DeleteModel(
            name='CreneauInscriptionEquipier',
        ),
    ]
