# Generated by Django 4.2.3 on 2023-07-20 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0003_creneauinscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneauinscription',
            name='periode',
        ),
        migrations.AddField(
            model_name='inscription',
            name='periode',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
