# Generated by Django 4.2.3 on 2023-08-05 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0003_remove_periode_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='nb_semaines',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
