# Generated by Django 4.2.3 on 2023-07-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0004_remove_creneauinscription_periode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='total_participations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
