# Generated by Django 4.2.3 on 2023-07-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0005_family_total_participations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creneauinscription',
            old_name='id_inscription',
            new_name='inscription',
        ),
    ]
