# Generated by Django 4.2.3 on 2023-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0006_rename_id_inscription_creneauinscription_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneauinscription',
            name='cycle_enfant',
        ),
        migrations.AddField(
            model_name='inscription',
            name='categorie',
            field=models.CharField(choices=[('C1', 'Cycle 1'), ('C2', 'Cycle 2'), ('C3', 'Cycle 3'), ('COL', 'College'), ('EQ', 'Equipier')], default='EQ', max_length=10),
            preserve_default=False,
        ),
    ]
